apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30080
      name: http
  selector:
    app: nginx